### ISSUE TITLE
issueのたてかたのドキュメントをgihubに作る

### ISSUE THREAD

**Issue by so1** [johokaigi/johokaigi_staff#3]
そんなにやり方難しくないけど、
ぼくはわからなかったので、練習がてらスクリーンショットなどとって
雑にissue.mdを作り、readme.mdからlinkしてあるとうれしい

**Comment by konishi** [comment]
- [GitHub Issueはテンプレート化で、綺麗に書かせる！ - Qiita](http://qiita.com/yoshimikeisui/items/3e1873e3bf1bbafe8733) これ便利そうなので共有まで〜 :package:

**Comment by tokifujp** [comment]
うぉぉぉ！ありがとうございます！

**Comment by tokifujp** [comment]
あら、またunassignされてる。。。

**Comment by konishi** [comment]
@Tokifujp すいませんrepositoryのcontributerに設定するのやめてorganizationに招待しなおしたので、JOINしなおしてもらえますか :bow: https://github.com/johokaigi にアクセスすると上にinvitationボタンが出ているはずなのでそちらから…

**Comment by tokifujp** [comment]
承知しました！後でメールみて気付きました！ありがとうございました！

**Comment by tokifujp** [comment]
オワタ ＼(^o^)／

**Comment by fakestarbaby** [comment]
おぉ、このファイルですね。
- [johokaigi_staff/issue.md at eac1434133eeb05e5a8335e0e5edd81584f90011 · johokaigi/johokaigi_staff](https://github.com/johokaigi/johokaigi_staff/blob/eac1434133eeb05e5a8335e0e5edd81584f90011/issue.md)

**Comment by so1** [comment]
ありがとー！
