### ISSUE TITLE
シェア太郎（情報会議のSlackにいるRuboty）にIssueを登録させる方法を書いてほしい

### ISSUE THREAD

**Issue by so1** [johokaigi/johokaigi_staff#6]
そもそも、ここにissueを登録できるようにして、使い方を記事にしておきたい

**Comment by so1** [comment]
別ファイルにしてリンクで繋ぎたい

**Comment by so1** [comment]
issueとしては、設定をして、新しいファイルをつくるところまで

**Comment by konishi** [comment]
シェア太郎にtokenを食わせてあげると、あとはslack上で `@sharetaro_bot: issue ほげほげ` でjohokaigi/johokaigiに、 `@sharetaro_bot: staff ほげほげ` でjohokaigi/johokaigi_staff にissueが作成できます。

**Comment by htomine** [comment]
![image](https://cloud.githubusercontent.com/assets/732828/11449878/0bc38004-95cb-11e5-9c10-45e916415b3a.png)

![image](https://cloud.githubusercontent.com/assets/732828/11449884/40a1790c-95cb-11e5-8f0c-b1bdac19caba.png)

![image](https://cloud.githubusercontent.com/assets/732828/11449911/720feeaa-95cc-11e5-99a1-4ae29be8edec.png)

![image](https://cloud.githubusercontent.com/assets/732828/11449917/9fa0772c-95cc-11e5-872b-5f975003821c.png)

![image](https://cloud.githubusercontent.com/assets/732828/11449934/045d0360-95cd-11e5-8d30-deb08804233e.png)

**Comment by htomine** [comment]
![image](https://cloud.githubusercontent.com/assets/732828/11450001/dabe12b8-95ce-11e5-81bf-9fbce33bd5f6.png)
