### ISSUE TITLE
#3報告ブログを書く

### ISSUE THREAD

**Issue by htomine** [johokaigi/johokaigi_staff#7]
- johokaigi.org にレポートをあげる
- なぜこの記事を読まなければいけないのか考えて設計する
  - どんな人がどう嬉しいのか

**Comment by konishi** [comment]
http://johokaigi.org/articles/2015/11/27/johokaigi-3-report.html すでに完了したと思われるのでcloseしておきます。問題があればreopenしてください :pray:

**Comment by so1** [comment]
ty
