### ISSUE TITLE
twitterから#johokaigino

### ISSUE THREAD

**Issue by so1** [johokaigi/johokaigi_staff#8]

**Comment by konishi** [comment]
@so1 テストで立てたように見えるのでcloseしますが、もしタイトルがおかしいだけだった場合はreopenとタイトルの修正をおねがいします〜 :pray:

**Comment by so1** [comment]
@konycc 
togetterを作る、って書きかけて途中で投稿しちゃったんですが
おわったのでcloseしなきゃいけないのに、ちゃんとかけてないからみっけられてなかったやつｗ
closeでokでした、ありがとうございます
